
services:
  app:
    build: .
    image: spring-mongo-app:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb+srv://brunoharison18:xE2NGihtznNYH9Hv@cluster0.cufza.mongodb.net/gestion-chambre?retryWrites=true&w=majority&appName=Cluster0
      - SERVER_PORT=8000
    ports:
      - "8090:8000"
    restart: unless-stopped
